sudo: required

services:
  - docker

language: java
dist: trusty

jdk:
  - openjdk8

script:
  - mvn clean package -U
  - docker build -t rso_socialno_omrezje/upravljanje_dogodkov .

after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push rso_socialno_omrezje/upravljanje_dogodkov
