kumuluzee:
  name: upravljanje_dogodkov-service
  version: 1.0.0
  env:
    name: dev
  config:
    start-retry-delay-ms: 500
    max-retry-delay-ms: 900000
    etcd:
      hosts: http://localhost:2379

rest-endpoints:
  katalog-dogodkov-url: "http://localhost:8080/v1/"